plugins {
	id 'net.fabricmc.fabric-loom-remap' version '1.16-SNAPSHOT'
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	mavenCentral()
	maven { url = "https://jitpack.io" }
	maven {
		name = "FzzyMaven"
		url = "https://maven.fzzyhmstrs.me/"
	}
	exclusiveContent {
		forRepository {
			maven {
				name = "Modrinth"
				url = "https://api.modrinth.com/maven"
			}
		}
		filter {
			includeGroup "maven.modrinth"
		}
	}
	maven { url = "https://maven.bawnorton.com/releases" }
}

loom {
	accessWidenerPath = file("src/main/resources/tameable-foxes.accesswidener")
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	modImplementation "me.fzzyhmstrs:fzzy_config:${project.fzzyConfigVersion}"

	modImplementation "maven.modrinth:not-enough-animations:1.9.3-1.20.1"
	modImplementation "maven.modrinth:companion:5.3.0+fabric"
	modImplementation "maven.modrinth:calm-down-dog:1.1.0"
	modImplementation "maven.modrinth:ecologics:2.2.6_1-Fabric"
	modImplementation "maven.modrinth:supplementaries:1.20-3.1.43-fabric"

	include(modImplementation(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-fabric:0.3.7-beta.2")))
	implementation(annotationProcessor("io.github.llamalad7:mixinextras-fabric:0.5.4"))
	include("io.github.llamalad7:mixinextras-fabric:0.5.4:slim")
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}
}