org.gradle.jvmargs=-Xmx2G -Dhttps.protocols=TLSv1.2,TLSv1.3
org.gradle.daemon=false
org.gradle.debug=false

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.115
neo_version_range=[21.1.115,)
loader_version_range=[1,)

fabric_version=0.107.0+2.0.23+1.21.1
fzzyConfigVersion=0.6.9+1.21

fzzy_config_range=[0.6.9+1.21,)
fabric_range=[0.107.0+2.0.23+1.21.1,)

mod_id=tameablefoxes
mod_name=Tameable Foxes
mod_license=MIT
mod_version=2.0.3-neoforge-1.21
mod_group_id=lancet_.tameable_foxes
mod_authors=Lancet_
mod_description=Small mod that makes foxes tameable
